### ISSUE TITLE
ErofsHandler: Detected EROFS filesystem but self.image_type is not ImageType.SYSTEM or ImageType.VENDOR

### ISSUE THREAD

**Issue by simos** [srlabs/extractor#8]
When running `extractor` on a vendor.img image, it returns the error message

```
Traceback (most recent call last):
  File "./extractor.py", line 2363, in <module>
    main()
  File "./extractor.py", line 65, in main
    extractor.extract(output_system_tar=args.tar_output, output_system_dir=args.system_dir_output, output_boot_img_path=output_boot_img_path, output_recovery_img_path=output_recovery_img_path, allow_missing_vendor=args.allow_missing_vendor)
  File "./extractor.py", line 2126, in extract
    next_handler = handler.get_next_handler()
  File "./extractor.py", line 2061, in get_next_handler
    check_result = handler.check()
  File "./extractor.py", line 1616, in check
    raise ValueError("ErofsHandler: Detected EROFS filesystem but self.image_type is not ImageType.SYSTEM or ImageType.VENDOR")
ValueError: ErofsHandler: Detected EROFS filesystem but self.image_type is not ImageType.SYSTEM or ImageType.VENDOR
```

Is this an issue similar to #3?

**Comment by dsirov** [comment]
+1

**Comment by thomasgroch** [comment]
+1
